language: nix
env:
  - EMACS_CI=emacs-25-1
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-27-1
before_install:
  # nix-emacs-ci
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

  # cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH

  # rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

  # ripgrep
  - cargo install ripgrep
install:
  - make deps
script:
  - emacs --version
  - make test
jobs:
  include:
    - stage: documentation
      env:
        - secure: iJ0dZerp1IGZMXHYNV9ciL/Uk09xeK91toBfEjj8dAWhs590WYVJ3CsSeYyTSowT9cTQeKxUilTg8KgmObPAoAz/Kwume409fb5sjPQgzBgaqE1JY/CSZopmWKbAv0xCauYxQFl+eKm8nS+uUBazOfAdcmUQzD61/KIKJYy7Ae1RTfv7udHXC8KExhwgscDqiXgvAv5M3WLVwG6DEEk03NA+tyff2AS+Lww7zAwn0ZF1hcWjtVEMhyHn08LrngLNCw4MoP4PN9FXGNhPfnMSVfpkkw7RrQUUVgL+x6+l1An+Nyuv4R9fGir1hRUq4DaLm5W3dzzPdKKtapDydG3HZDC9by4yTi5mzxqO+O75x71Y8dNR/A5wg2dDx7+7Hyn8/ARbBvVHGtxyE/8MvlMakJhRJ9EXBKmjnq6O3qQk2BmbgSSkAGDxWvOTDgo2TlZ1Irn6secnVNZiHalqWmxKcUjFjXDJu3+2WHCrJoUxSsvW/fmKQNn3KV+jxjlukRoV5C3ONpa5QmmrAsdQJIj2rImhhtVN5SZUR5Nbv56y5/uoZvp5vicZ+dJRK3aZ5DvUQe7a3/XP6L/gDRPBL9uG3GjleRm13F7osQzmxjXAjfNrDEF9k/Lb9bmpCephqqFtx9R/cypBjRtdDyjhFvVyNhQOLgM4E7Ezv2Nv7jby97Y=
        - EMACS_CI=emacs-27-1
      script:
        - make rst
      deploy:
        # Branch changes are committed to master branch
        - provider: pages
          github_token: $GITHUB_API_KEY
          skip_cleanup: true
          keep_history: true
          local_dir: docs/rst
          repo: dajva/rg.el-docs
          target_branch: master
          verbose: true
          on:
            branch: master
        # Tagged changes are committed to release branch
        - provider: pages
          github_token: $GITHUB_API_KEY
          skip_cleanup: true
          keep_history: true
          local_dir: docs/rst
          repo: dajva/rg.el-docs
          target_branch: release
          verbose: true
          on:
            tags: true
      # Tag the documentation repository if needed.
      after_deploy: |
        if [ -n "$TRAVIS_TAG" ]; then
          git clone https://github.com/dajva/rg.el-docs
          cd rg.el-docs
          git checkout release
          TAG=${TRAVIS_TAG}
          git tag $TAG
          git push https://dajva:$GITHUB_API_KEY@github.com/dajva/rg.el-docs $TAG
        fi
