name: Build
on:
  push:
  release:
    types:
      - created
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.2
    steps:
    - name: Setup emacs-ci-nix for ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Setup Cask
      run: |
        curl -fsSkL https://raw.github.com/cask/cask/master/go | python
        echo "$HOME/.cask/bin" >> $GITHUB_PATH
    - name: Install rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
    - name: Install ripgrep
      run: cargo install ripgrep
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install emacs deps
      run: make deps
    - name: Run tests
      run: |
        emacs --version
        make test
  documentation:
    runs-on: ubuntu-latest
    # needs: tests
    if: github.ref == 'refs/heads/github_actions' || github.event_name == 'release'
    steps:
    - name: Setup emacs-ci-nix for emacs 27.2
      uses: purcell/setup-emacs@master
      with:
        version: 27.2
    - name: Setup Cask
      run: |
        curl -fsSkL https://raw.github.com/cask/cask/master/go | python
        echo "$HOME/.cask/bin" >> $GITHUB_PATH
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install emacs deps
      run: make deps
    - name: Generate restructured text
      run:  make rst
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: test_github_actions
        folder: docs/rst
        repository-name: dajva/rg.el-docs
        token: ${{ secrets.DOCUMENTATION_DEPLOYMENT }}
    - name: Tag release
      if: github.event_name == 'release'
      run: echo "Tagging"
