name: Build
on:
  push:
  release:
    types:
      - created
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.2
    steps:
    - name: Setup emacs-ci-nix for ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Setup Cask
      uses: conao3/setup-cask@master

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install ripgrep
      run: cargo install ripgrep

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install emacs deps
      run: make deps

    - name: Run tests
      run: |
        emacs --version
        make test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: emacs-${{ matrix.emacs_version }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

